title: Welcome to my homepage
description: Thomas Chen
show_downloads: false
google_analytics:
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/architect@v0.2.0
github.is_user_page: false
